#!/bin/bash
DIR=$(pwd)
echo "pulling rsnap"
git pull
echo "cd to app assets"
cd $DIR/app/assets/javascripts/snap-byob
echo "pulling snap"
git pull
echo "cd to lib assets"
cd $DIR/lib/assets/javascripts/snap-byob
echo "pulling snap"
git pull
echo "cd back to rsnap"
cd $DIR
