#!/bin/bash
echo "Enter the url from where RSnap was available (your server's url)"
read server_url
pg_dump -d rsnap_development -f rsnap_development.dump
rm dump.zip
sed -i -e "s/$server_url/localhost/g" rsnap_development.dump
zip -r dump.zip public rsnap_development.dump
rm rsnap_development.dump