# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)}, 
file = Tempfile.new(["temp", ".xml"], "#{Rails.root}/tmp")
file.write(File.read("#{Rails.root}/public/default_mission.xml"))
file.rewind
users = User.create!([{firstname: "Simon", lastname: "Hock", email: "simon.hock@hotmail.com",password: "rsnap", password_confirmation: "rsnap", type: 'Admin'}])
missions = Mission.create!([
{title:  "Anime la souris.", 						description: "Dans cette toute première mission, tu apprendras à utiliser l'environnement de programmation. <br><br>Ton but sera de déplacer la souris <br><br>Pour cela, tu devras utiliser le bloc <img alt=\"bouger_aleatoirementpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/055/original/bouger_aleatoirement.png?1426250895\">. Si ce bloc est attaché au bloc <img alt=\"bloc_demarrerpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/057/original/bloc_demarrer.png?1426250930\"> comme ceci: <img alt=\"bouger_aleatoirement_attachpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/056/original/bouger_aleatoirement_attach%C3%A9.png?1426250895\">, la souris s'animera une fois qu'on appuiera sur démarrer&nbsp;<img alt=\"demarrerpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/074/original/demarrer.png?1426253564\"> <br><br>Pour cela, il faudra que du déplace le bloc <img alt=\"bouger_aleatoirementpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/055/original/bouger_aleatoirement.png?1426250895\"> de la liste à gauche jusqu'en dessous du bloc <img alt=\"bloc_demarrerpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/057/original/bloc_demarrer.png?1426250930\">. Assure-toi qu'il est bien attaché comme ceci: <img alt=\"bouger_aleatoirement_attachpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/056/original/bouger_aleatoirement_attach%C3%A9.png?1426250895\"><br><br> Pour lancer ton programme appuie sur le petit drapeau vert en haut a droite de l’écran <span><img alt=\"demarrerpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/032/original/demarrer.png?1425985849\">.</span> <br><br>Tu as aussi le choix de faire avancer avec la souris avec le bloc <img alt=\"bloc_avancerpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/054/original/bloc_avancer.png?1426250895\">.<br><br>", small_description: "Apprends à déplacer la souris sur le plateau !! <br><img alt=\"souris-droitepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/096/original/souris-droite.png?1440244193\"><br>", source_code: file, teacher: users.first }, 
{title:  "Aide la souris à arriver au fromage !", 	description: "La souris se retrouve sur une poutre et il y a un fromage tout au bout ! <br><br>Pour cela, il faudra que tu la fasses avancer plusieurs fois, ajoute les blocs <img alt=\"bloc_avancerpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/058/original/bloc_avancer.png?1426251070\"> les uns à la suite des autres pour qu'elle arrive jusqu'au fromage ! <br><br>Fais attention de ne pas aller trop loin !<br><br>Astuce: Avancer 3 fois sera suffisant !<br><br>", small_description: "<img alt=\"fromagepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/098/original/fromage.png?1440244484\"><img alt=\"\" src=\"http://\"><br>", source_code: file, teacher: users.first }, 
{title:  "Attention au tournant !", 				description: "Te revoici à aider la souris à attraper son fromage !!<br><br>Cette fois c'est un peu plus compliqué, la poutre n'est plus droite !<br>Aide la souris à tourner dans la bonne direction avec le bloc&nbsp;<img src=\"http://192.168.1.4/system/file_missions/files/000/000/059/original/bloc_tourner_%C3%A0_gauche.png?1426251102\" alt=\"bloc_tourner__gauchepng\"> pour qu'elle arrive au fromage !<br><br>Fais attention: la souris doit avancer plusieurs fois pour chaque ligne droite.,", small_description: "Virage à gauche !<br>", source_code: file, teacher: users.first }, 
{title:  "Le Labyrinthe", 							description: "descrciption: Maintenant la souris est dans un plus grand labyrinthe, fais attention \r\naux tournants et à bien compter le nombre de fois qu'elle devra avancer !<br><br>", small_description: "Attention à ne pas te perdre !<br><br>", source_code: file, teacher: users.first }, 
{title:  "En voiture : Prendre les commandes!", 	description: "Dans cette première mission, ton but de faire une grande\r\n ligne droite mais en n'utilisant qu'un seul bloc <img alt=\"bloc_avancer_depng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/061/original/bloc_avancer_de.png?1426251148\">. <br><br>Pour cela, il te faudra faire avancer la voiture de la \r\nbonne distance ! <br>Pour le moment tu as déjà dans la partie script le bloc <img alt=\"bloc_demarrerpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/060/original/bloc_demarrer.png?1426251142\">. Rajoute un bloc <img alt=\"bloc_avancer_depng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/061/original/bloc_avancer_de.png?1426251148\"> et change le nombre qui s'y trouve pour arriver au bout de la ligne droite.<span><br><br>Pour lancer ton programme, appuie sur le petit drapeau vert en haut a droite de l’écran <img alt=\"demarrerpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/079/original/demarrer.png?1427120826\">.</span> <br><br><br><br>", small_description: "En avant !!<br><h1><img alt=\"voiture-droitepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/097/original/voiture-droite.png?1440244290\"></h1>", source_code: file, teacher: users.first }, 
{title:  "En voiture : Un virage à gauche !", 		description: "Maintenant que tu es arrivé au bout de la ligne droite, fais tourner la \r\nvoiture à gauche et fais la avancer à nouveau !<br><br>La\r\n voiture devra faire un angle droit sur la gauche, refais la même chose \r\nque dans la mission précédente, ajoute le bloc <img src=\"http://192.168.1.4/system/file_missions/files/000/000/063/original/bloc_tourner_%C3%A0_gauche.png?1426251213\" alt=\"bloc_tourner__gauchepng\"> et ajoute encore le bloc <img src=\"http://192.168.1.4/system/file_missions/files/000/000/062/original/bloc_avancer_de.png?1426251212\" alt=\"bloc_avancer_depng\"> en changeant le nombre qui s'y trouve.<br><br><br>", small_description: "Tourne le volant !<br><br>", source_code: file, teacher: users.first }, 
{title:  "En voiture : Le tour du circuit !", 		description: "Maintenant que tu as compris comment les blocs fonctionnent, fais le tour du circuit !!<br><br>Ajuste par toi-même les distances !<br><br>", small_description: "<img src=\"http://192.168.1.4/system/file_missions/files/000/000/043/original/ligne_d%27arriv%C3%A9e.jpeg?1425986153\" alt=\"ligne_darrivejpeg\">", source_code: file, teacher: users.first }, 
{title:  "La ligne droite.", 						description: "Fais avancer l'escargot pour qu'il recouvre la ligne noire !<br><br>Dans cette mission, tu n'auras besoin que du bloc <img alt=\"bloc_avancer_depng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/064/original/bloc_avancer_de.png?1426251274\">.<br><br>Astuce: il doit avancer d'un chiffre rond.<br><br>", small_description: "<img alt=\"\"><img alt=\"escargot-droitepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/095/original/escargot-droite.png?1440244143\"><img alt=\"\">", source_code: file, teacher: users.first }, 
{title:  "Un carré.", 								description: "Maintenant que tu as vu la trace que l'escargot laisse derrière lui, fais-lui effacer le carré noir!<br><br>Il devra avancer 4 fois et tourner aussi 4 fois :-)<br><br>", small_description: "<img src=\"http://192.168.1.4/system/file_missions/files/000/000/048/original/Escargot_carr%C3%A9.png?1426104194\" alt=\"Escargot_carrpng\">", source_code: file, teacher: users.first }, 
{title:  "Un triangle", 							description: "Dessine-nous un triangle !<br><br>Pour cela, il te faudra avancer 3 fois de 15 et tourner 3 fois de 120 degrés sur la gauche.<br><br>Assure-toi de bien mettre \"120\" dans les blocs <img src=\"http://192.168.1.4/system/file_missions/files/000/000/065/original/bloc_tourner_%C3%A0_gauche_de.png?1426251417\" alt=\"bloc_tourner__gauche_depng\"> et de mettre \"15\" dans les blocs <img src=\"http://192.168.1.4/system/file_missions/files/000/000/067/original/bloc_avancer_de.png?1426251470\" alt=\"bloc_avancer_depng\">.<br><br>", small_description: "<img src=\"http://192.168.1.4/system/file_missions/files/000/000/049/original/Escargot_triangle.png?1426249903\" alt=\"Escargot_trianglepng\">", source_code: file, teacher: users.first }, 
{title:  "Ta première boucle", 						description: "Une boucle est une façon de répéter des actions un certain nombre de fois.<br><br>Sur notre plateforme, les boucles sont comme ceci:<br><img src=\"http://192.168.1.4/system/file_missions/files/000/000/068/original/bloc_boucler_x_fois.png?1426251637\" alt=\"bloc_boucler_x_foispng\"><br><br>Tous les blocs qui seront à l'intérieur de cette boucle seront répétés un certain nombre de fois.<br>Le nombre de fois que les actions seront répétées est défini dans le bloc lui-même. <br>Par exemple, le bloc <img src=\"http://192.168.1.4/system/file_missions/files/000/000/070/original/bloc_boucler_4_fois_-_avancer.png?1426251794\" alt=\"bloc_boucler_4_fois_-_avancerpng\"> répétera 4 fois <img src=\"http://192.168.1.4/system/file_missions/files/000/000/069/original/bloc_avancer.png?1426251794\" alt=\"bloc_avancerpng\">.<br><br>Tu peux y ajouter plusieurs blocs, et donc faire par exemple avancer et puis tourner et recommencer.<br><br>Par exemple :<br><img src=\"http://192.168.1.4/system/file_missions/files/000/000/071/original/bloc_boucler_3_fois_-_avancer_15_tourner_120.png?1426251902\" alt=\"bloc_boucler_3_fois_-_avancer_15_tourner_120png\"><br><br>Fais faire un carré à l'escargot! <br><br><br>", small_description: "<img src=\"http://192.168.1.4/system/file_missions/files/000/000/072/original/bloc_boucler_x_fois.png?1426251934\" alt=\"bloc_boucler_x_foispng\">", source_code: file, teacher: users.first }, 
{title:  "Un triangle bouclé.", 					description: "Maintenant que tu as vu comment les boucles fonctionnent,<br><br>Re-dessine le triangle avec une boucle ! <br><br>La boucle est déjà là, ajoutes-y les blocs pour avancer et tourner !<br><br>Astuce: Les distances et les angles n'ont pas changés depuis le dernier triangle !<br><br><br>", small_description: "<img src=\"http://192.168.1.4/system/file_missions/files/000/000/073/original/Escargot_triangle_color%C3%A9.png?1426252600\" alt=\"Escargot_triangle_colorpng\">", source_code: file, teacher: users.first }, 
{title:  "L'hexagone", 								description: "Dessine un hexagone !<br><br>Un hexagone est fait de 6 côtés.<br><br>Astuce: Tu devras tourner de 360 degrés au total !<br>", small_description: "<img src=\"http://192.168.1.4/system/file_missions/files/000/000/082/original/Escargot_hexagone.png?1427186113\" alt=\"Escargot_hexagonepng\"><img src=\"http://\" alt=\"\"><br>", source_code: file, teacher: users.first }, 
{title:  "Le cercle", 								description: "Dessine un cercle !<br><br>Utilise comme la dernière fois les blocs avancer et tourner qui sont à ta disposition.<br><br>Astuce: tu ne devrais pas avoir besoin de plus de blocs que ce qu'il y a déjà.<br>", small_description: "<img alt=\"Escargot_cerclepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/076/original/Escargot_cercle.png?1426256441\">", source_code: file, teacher: users.first }, 
{title:  "Les spirographes", 						description: "Maintenant que tu as compris comment faire des boucles, <br><br>Amuse-toi à dessiner ce que tu veux !!<br><br><br><br>", small_description: "<img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Various_Spirograph_Designs.jpg/220px-Various_Spirograph_Designs.jpg\" alt=\"\" height=\"158\" width=\"220\"><br>", source_code: file, teacher: users.first }, 
{title:  "Pointillons", 							description: "Dans cette première mission, nous allons introduire le nouveau bloc \"Avancer de ... sans dessiner\".<br><br>Grâce à ce bloc, tu peux faire avancer l'escargot sans qu'il dessine!<br><br>Fais le avancer 20 fois en alternant dessiner et ne pas dessiner.<br><br><br>", small_description: "<img src=\"http://192.168.1.4/system/file_missions/files/000/000/083/original/Escargot_pointillons.png?1427186151\" alt=\"Escargot_pointillonspng\"><img src=\"http://\" alt=\"\"><br>", source_code: file, teacher: users.first }, 
{title:  "Une boucle dans une boucle!", 			description: "Cette mission est un point critique !<br><br>Les boucles peuvent être imbriquées les unes dans les autres, comme ceci :<br><img src=\"http://192.168.1.4/system/file_missions/files/000/000/084/original/boucle_imbriqu%C3%A9e.png?1427186194\" alt=\"boucle_imbriquepng\"><img src=\"http://\" alt=\"\"><br><br>Dans cet exemple, l'escargot avancera 8 fois et tournera 4 fois !<br><br>Dans cette mission ci, tu as déjà une boucle pour faire une ligne en pointillé. <br><br>Ajoutes-y un bloc à la sortie de la boucle pour faire tourner l'escargot vers la gauche et met le tout dans une boucle qui répétera 2 fois !<br>", small_description: "<img src=\"http://192.168.1.4/system/file_missions/files/000/000/085/original/Escargot_pointillons_coin.png?1427186265\" alt=\"Escargot_pointillons_coinpng\"><img src=\"http://\" alt=\"\"><br>", source_code: file, teacher: users.first },
{title:  "Un carré en pointillés.", 				description: "Tu es arrivé jusqu'à la moitié d'un carré !<br><br>Fais 4 lignes en pointillé comme tu as fait les missions précédentes !<br><br><br>", small_description: "<img src=\"http://192.168.1.4/system/file_missions/files/000/000/086/original/Escargot_pointillons_carr%C3%A9.png?1427186451\" alt=\"Escargot_pointillons_carrpng\"><img src=\"http://\" alt=\"\"><br>", source_code: file, teacher: users.first }, 
{title:  "Les 4 triangles!", 						description: "<br>Dessine quatre triangles en faisant 90 degrés entre chaque triangle.<br><br>Tu aura plus facile si tu commence d'abord par faire toute la boucle qui crée un triangle.<br>Ensuite de le mettre dans la grande boucle!<br>", small_description: "<img src=\"http://192.168.1.4/system/file_missions/files/000/000/087/original/Escargot_4_triangles.png?1427186501\" alt=\"Escargot_4_trianglespng\"><img src=\"http://\" alt=\"\"><br>", source_code: file, teacher: users.first }, 
{title:  "Les 3 carrés", 							description: "Super !!<br><br>Tu as réussi à arriver jusqu'ici, ça veut dire que tu es un as !<br><br>Amuse-toi à dessiner 3 carrés!<br><br>Fais tourner l'escargot de 120 degrés vers la gauche entre chaque carré.<br><br>Astuce:\r\n Fais d'abord la boucle du carré (avec des cotés de 5) <br><br><br>", small_description: "<img src=\"http://192.168.1.4/system/file_missions/files/000/000/081/original/Escargot_3_carr%C3%A9s.png?1427186089\" alt=\"Escargot_3_carrspng\"><img src=\"http://\" alt=\"\"><img src=\"http://\" alt=\"\"><br>", source_code: file, teacher: users.first }, 
{title:  "Des nouveaux spirographes", 				description: "Les boucles imbriquées sont super intéressantes pour faire des dessins!<br><br>Amuse toi à nouveau à dessiner ce que tu veux !<br>", small_description: "<img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Various_Spirograph_Designs.jpg/220px-Various_Spirograph_Designs.jpg\" alt=\"\" height=\"158\" width=\"220\"><br>", source_code: file, teacher: users.first }, 
{title:  "Le chercheur d'or", 						description: "Cherchons l'or et les pierres précieuses ensemble !<br><br>Quand le \r\nchercheur d'or passe sur une case il la découvre, fait lui découvrir les\r\n cases devant lui et fait lui ramasser les pierres précieuses qu'il \r\nrencontre<br><br>Il vas falloir que tu lui fasse découvrir les quelques cases devant lui !<br><br>Utilise le bloc <img alt=\"bloc_sipng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/089/original/bloc_si.png?1427446696\"><img alt=\"\" src=\"http://\"> et ajoute <img alt=\"bloc_a_trouv_des_pierrespng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/090/original/bloc_a_trouv%C3%A9_des_pierres.png?1427446718\">.<br><br>à l'intérieur du bloc <img alt=\"bloc_sipng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/089/original/bloc_si.png?1427446696\">, tu peux ajouter des blocs d'action, comme on faisait dans les boucles !<br>Ces blocs ne seront activés que si la condition que tu as mis dans le \"si\" est vraie.<br><br>Par exemple:<br><img alt=\"bloc_si_peut_avancer_avancepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/091/original/bloc_si_peut_avancer_avance.png?1427446718\"><br><br>Cet ensemble fera avancer le personnage seulement si il peut avancer !<br><br>Dans les prochaines missions, tu vas devoir faire ramasser des pierres précieuses au chercheur d'or.<br><br>Fais attention qu'il n'est plus tout jeune! Il ne sera pas content si tu lui fais s'abaisser pour ne rien ramasser !<br><br><br><br><br><br>", small_description: "<img alt=\"ppitepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/100/original/p%C3%A9pite.png?1440244529\"><img alt=\"\" src=\"http://\">", source_code: file, teacher: users.first },
{title:  "Le diamant !", 							description: "<br>Le principe de cette mission est le même, déplace le chercheur d'or pour qu'il trouve toutes les pierres précieuses !<br><br>Astuce: il y en a une dans chaque couloir !<br>", small_description: "<img alt=\"diamantpng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/099/original/diamant.png?1440244505\"><img alt=\"\" src=\"http://\">", source_code: file, teacher: users.first }])

chapters = Chapter.create!([
{title:  "La souris.", 										description: "Dans ce petit chapitre, tu vas apprendre à utiliser l'environnement de programmation en faisant se déplacer une souris sur le plateau. <br><img alt=\"souris-droitepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/096/original/souris-droite.png?1440244193\"><br><br><br>", small_description: "<img alt=\"souris-droitepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/096/original/souris-droite.png?1440244193\"><br>", teacher: users.first}, 
{title:  "En voiture !", 									description: "<h1><img alt=\"voiture-droitepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/097/original/voiture-droite.png?1440244290\"><img alt=\"\" src=\"http://\"><br></h1><br>Pour\r\n ce chapitre, tu vas prendre place dans un bolide et tenter de rejoindre\r\n la ligne d’arrivée dans ta voiture. <br><br>Nous allons ici introduire le nouveau bloc: <img alt=\"bloc_avancer_depng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/102/original/bloc_avancer_de.png?1440248866\"><img alt=\"\" src=\"http://\"><br>Comme tu peux le voir dans ce bloc, il y a un nombre. Celui-ci définit la distance que tu souhaites parcourir. Il peut être modifié en cliquant dans la zone blanche où il se trouve. <br><br>Par exemple: Si tu veux avancer de 2 cases, tu dois obtenir ceci:&nbsp;<img alt=\"avancer_de_2png\" src=\"http://192.168.1.4/system/file_missions/files/000/000/103/original/avancer_de_2.png?1440248866\">.<br><br>Fais attention, les circuits deviennent de plus en plus longs et sinueux ! <br><br>Ne fais pas sortir la voiture du circuit, sinon ... BOUM !<br><br>", small_description: "<h1><img alt=\"voiture-droitepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/097/original/voiture-droite.png?1440244290\"></h1>", teacher: users.first}, 
{title:  "L'escargot.", 									description: "Dans ce chapitre, tu vas apprendre à déplacer ton personnage dans toutes les directions!<br><br>Maintenant\r\n que tu as compris comment fonctionne le bloc&nbsp;<img alt=\"bloc_avancer_depng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/106/original/bloc_avancer_de.png?1440249728\">, on va \r\nintroduire le bloc&nbsp;<img alt=\"bloc_tourner__droite_depng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/107/original/bloc_tourner_%C3%A0_droite_de.png?1440249729\">&nbsp;et le bloc <img alt=\"bloc_tourner__gauche_depng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/108/original/bloc_tourner_%C3%A0_gauche_de.png?1440249729\"><img alt=\"\" src=\"http://\">.<br><br>Ces deux blocs vont faire tourner ton personnage vers sa droite ou sa gauche d'un certain angle. <br><br>En se déplaçant, l'escargot laissera une trace derrière lui. Fais-lui dessiner ce qu'on demande !!<br>", small_description: "<img alt=\"\" src=\"http://\"><img alt=\"escargot-droitepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/095/original/escargot-droite.png?1440244143\"><img alt=\"\" src=\"http://\">", teacher: users.first}, 
{title:  "Les boucles ... Oui mais dans des boucles !!", 	description: "Attention !! <br><br>Les choses se corsent...<br><br>Dans ce chapitre, on va te faire voir des boucles dans tous les sens !<br><br><br>", small_description: "<img alt=\"Escargot_pointillonspng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/101/original/Escargot_pointillons.png?1440246362\"><img alt=\"\" src=\"http://\"><br>", teacher: users.first}, 
{title:  "Oui mais !!", 									description: "Dans ce chapitre, tu vas apprendre à utiliser des conditions simples.<br><br>Ton but dans ce chapitre est d'aider un vieux chercheur d'or à ramasser des pierres précieuses !<br><br><br>", small_description: "<img alt=\"chercheur-centrepng\" src=\"http://192.168.1.4/system/file_missions/files/000/000/109/original/chercheur-centre.png?947427583\"><img alt=\"\" src=\"http://\">", teacher: users.first}
])

courses = Course.create!([{title: "Cours de base", description: "Cours de base enseignant les notions de base de la programmation tels que la séquentialité, les boucles, ...", teacher: users.first}])

chapters.first.add_mission(missions[0])
chapters.first.add_mission(missions[1])
chapters.first.add_mission(missions[2])
chapters.first.add_mission(missions[3])

chapters.second.add_mission(missions[4])
chapters.second.add_mission(missions[5])
chapters.second.add_mission(missions[6])

chapters.third.add_mission(missions[7])
chapters.third.add_mission(missions[8])
chapters.third.add_mission(missions[9])
chapters.third.add_mission(missions[10])
chapters.third.add_mission(missions[11])
chapters.third.add_mission(missions[12])
chapters.third.add_mission(missions[13])
chapters.third.add_mission(missions[14])


chapters.fourth.add_mission(missions[15])
chapters.fourth.add_mission(missions[16])
chapters.fourth.add_mission(missions[17])
chapters.fourth.add_mission(missions[18])
chapters.fourth.add_mission(missions[19])
chapters.fourth.add_mission(missions[20])

chapters.fifth.add_mission(missions[21])
chapters.fifth.add_mission(missions[22])

courses.first.add_chapter(chapters.first)
courses.first.add_chapter(chapters.second)
courses.first.add_chapter(chapters.third)
courses.first.add_chapter(chapters.fourth)
courses.first.add_chapter(chapters.fifth)